version: '3.8'

services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    env_file:
      - .env
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - rag-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rag-frontend
    ports:
      - "3000:3000"
    depends_on:
      - rag-app
    restart: unless-stopped
    networks:
      - rag-network
    environment:
      - NEXT_PUBLIC_API_URL=http://rag-app:8000

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  qdrant-data:
    driver: local