version: '3.8'

services:
  rag-app:
    image: ${DOCKERHUB_USERNAME}/backend:latest
    container_name: rag-app
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - qdrant
    restart: unless-stopped
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    container_name: rag-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://34.30.191.213:8000
    depends_on:
      - rag-app
    restart: unless-stopped
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rag-app
      - frontend
    restart: unless-stopped
    networks:
      - rag-network

volumes:
  qdrant-data:

networks:
  rag-network:
    driver: bridge
