name: Build and Push Docker Images

on:
  push:
    branches:
      - test/cicd

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Create backend .env file
        run: echo "${{ secrets.BACKEND_ENV }}" > src/.env

      - name: Create frontend .env file
        run: echo "${{ secrets.FRONTEND_ENV }}" > frontend/.env

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/frontend:latest 