name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image tag to rollback to (default: previous)'
        required: false
        default: 'previous'

jobs:
  rollback:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
    
    steps:
      - name: Rollback deployment on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USER }}
          key: ${{ env.VPS_SSH_KEY }}
          script: |
            cd /home/${{ env.VPS_USER }}/app
            
            echo "🔄 Rolling back to previous version..."
            
            # Stop current containers
            docker-compose down
            
            # Pull previous version (you can specify tag in input)
            if [ "${{ github.event.inputs.version }}" = "previous" ]; then
              echo "Rolling back to previous image tags..."
              # List available tags and use second latest
              docker pull ${{ env.DOCKERHUB_USERNAME }}/backend:latest
              docker pull ${{ env.DOCKERHUB_USERNAME }}/frontend:latest
            else
              echo "Rolling back to specified version: ${{ github.event.inputs.version }}"
              docker pull ${{ env.DOCKERHUB_USERNAME }}/backend:${{ github.event.inputs.version }}
              docker pull ${{ env.DOCKERHUB_USERNAME }}/frontend:${{ github.event.inputs.version }}
              
              # Update docker-compose to use specific version
              sed -i "s/:latest/:${{ github.event.inputs.version }}/g" docker-compose.yml
            fi
            
            # Start containers with previous version
            docker-compose up -d
            
            # Wait for services to be ready
            sleep 30
            
            # Check health
            echo "🩺 Checking service health..."
            curl -f http://localhost:8000/health || echo "Backend health check failed"
            curl -f http://localhost:3000 || echo "Frontend health check failed"
            
            echo "✅ Rollback completed!"
